bump_version: null
lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-gemmicroflow_logo_light.png
  - docs/images/nf-core-gemmicroflow_logo_light.png
  - docs/images/nf-core-gemmicroflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-gemmicroflow_logo_light.png
  - docs/images/nf-core-gemmicroflow_logo_light.png
  - docs/images/nf-core-gemmicroflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Francesc Catala Moll
  description: MicroFlow Analyzer is a Nextflow-based pipeline for comprehensive microbiome
    FASTQ analysis. It integrates taxonomic profiling, functional annotation, Integrated
    Gene Catalog (IGC) analysis, and Metagenome-Assembled Genomes (MAGs) reconstruction.
  force: true
  is_nfcore: false
  name: gemmicroflow
  org: MicrobialGenomics-IrsicaixaOrg
  outdir: .
  skip_features: []
  version: 1.0.0dev
update: null
